### ISSUE TITLE
Sanity studio V3 support

### ISSUE THREAD

**Issue by AidanRRR** [sanity-io/sanity-plugin-studio-smartling#18]
Hey, there is a warning on the [plugin page](https://www.sanity.io/plugins/sanity-plugin-studio-smartling) that this only works with Sanity Studio V2.

Is support planned for version 3?

Thanks

**Comment by wdtamagi** [comment]
I'm looking forward to know the answer as well.

**Comment by cngonzalez** [comment]
Hi both! Apologies for the delay here. We are hoping to roll out a v3 version of the existing functionality within the week.

**Comment by AidanRRR** [comment]
> I'm looking forward to know the answer as well.

You can use [this](https://github.com/AidanRRR/sanity-plugin-studio-v3-smartling) as a temporary solution

**Comment by wdtamagi** [comment]
Great news @cngonzalez.

Thank you @AidanRRR !

**Comment by cngonzalez** [comment]
Thanks very much Aidan! And thank you for your patience, all.

I've published a beta version of the v3 plugin. Feel free to try it out with `npm install sanity-plugin-studio-smartling@beta`. I'll post back in this thread when it's mainline. Please be aware of a breaking change in the v3 version; the proxy location should now be kept in your secrets document. This is to streamline different environments the Sanity studio may be part of in the future.
 
 There's more information in [that branch's README](https://github.com/sanity-io/sanity-plugin-studio-smartling/tree/chore/update-to-studio-v3#migrating-to-sanity-studio-v3).
 
 I'm keeping this in beta because I'm noticing odd behavior around progress coming from the Smartling API (to be clear -- this is also affecting v2 versions of the plugin). The completion numbers coming back always start at 50%, and scale strangely. I'm getting in touch with their team to see if this is a new bug, or if that logic should be replaced.

**Comment by cngonzalez** [comment]
Thank you for your patience, all. 3.0.0 is out. All changes required have been documented in the [README].(https://github.com/sanity-io/sanity-plugin-studio-smartling#migrating-to-sanity-studio-v3)

**Comment by aidan-rypens** [comment]
@cngonzalez thanks for the effort!! works perfectly
